image: gitpod/workspace-mysql

tasks:
    - init: mysql -u root -e "CREATE DATABASE goldstar"; mysql -u root goldstar < ./assets/sql/schema.mysql.sql; mysql -u root goldstar < ./assets/sql/initdb.mysql.sql
